export type CategoryIds = 'hoodies' | 'tshirts'
export type SizeName = 'XXS' | 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL'

type Item = {
  id: string
  name: string
  brand: string
  category: CategoryIds
  type: 'men' | 'women' | 'kids' | 'babies'
  sizes: { name: SizeName; inStock: boolean }[]
  price: number
  rating: number
  reviewCount: number
  colors: string[]
  description: string
  imgUrl: string
  url: string
}

module.exports = {
  categories: <{ id: CategoryIds; name: string }[]>[
    {
      id: 'hoodies',
      name: 'Hoodies',
    },
    {
      id: 'tshirts',
      name: 'T-shirts',
    },
    {
      id: 'shirts',
      name: 'Shirts',
    },
    {
      id: 'shorts',
      name: 'Shorts',
    },
    {
      id: 'pants',
      name: 'Pants',
    },
    {
      id: 'jeans',
      name: 'Jeans',
    },
    {
      id: 'suits',
      name: 'Suits',
    },
  ],
  products: <Item[]>[
    {
      id: 'relaxed-fit-hoodie-0',
      name: 'Relaxed-fit Hoodie',
      brand: 'H&M',
      category: 'hoodies',
      type: 'men',
      sizes: [
        { name: 'XXS', inStock: true },
        { name: 'XS', inStock: true },
        { name: 'S', inStock: false },
        { name: 'M', inStock: true },
        { name: 'L', inStock: true },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
        { name: 'XXXL', inStock: false },
      ],
      price: 30000,
      rating: 4.2,
      reviewCount: 102,
      colors: ['turquoise', 'black', 'white'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/8e/84/8e844b68bda70cd91762a7b1e83e8091436cc63d.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0970819019.html',
    },
    {
      id: 'regular-fit-hoodie-0',
      name: 'Regular Fit Hoodie',
      brand: 'H&M',
      category: 'hoodies',
      type: 'men',
      sizes: [
        { name: 'XXS', inStock: false },
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: true },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
        { name: 'XXXL', inStock: false },
      ],
      price: 25000,
      rating: 4.6,
      reviewCount: 29,
      colors: ['black', 'brown'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/a2/4c/a24ccf6fa3f58a3f9e37d0ac138af4278067f9a1.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.1010387004.html',
    },
    {
      id: 'simpsons-regular-fit-hoodie-0',
      name: 'Simpsons Regular Fit Hoodie',
      brand: 'H&M',
      category: 'hoodies',
      type: 'men',
      sizes: [
        { name: 'XXS', inStock: true },
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: true },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
        { name: 'XXXL', inStock: false },
      ],
      price: 35000,
      rating: 2.0,
      reviewCount: 5,
      colors: ['purple', 'pink', 'white'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/58/61/5861ba00223582ce344bf7febefabdd157a80a5f.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0846933078.html',
    },
    {
      id: 'tie-dye-print-sweatshirt-0',
      name: 'TIE-DYE PRINT SWEATSHIRT',
      brand: 'Zara',
      category: 'hoodies',
      type: 'men',
      sizes: [
        { name: 'XXS', inStock: true },
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: true },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
        { name: 'XXXL', inStock: false },
      ],
      price: 89000,
      rating: 3.0,
      reviewCount: 4,
      colors: ['purple', 'pink', 'white'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://static.zara.net/photos///2021/I/0/2/p/0840/302/609/2/w/608/0840302609_2_4_1.jpg?ts=1628241476608',
      url: 'https://www.zara.com/kr/en/tie-dye-print-sweatshirt-p00840302.html',
    },
    {
      id: '2-pack-long-fit-tshirt-0',
      name: '2-pack Long Fit T-shirt',
      brand: 'H&M',
      category: 'tshirts',
      type: 'men',
      sizes: [
        { name: 'XXS', inStock: true },
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: true },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
        { name: 'XXXL', inStock: false },
      ],
      price: 9000,
      rating: 2.5,
      reviewCount: 20,
      colors: ['gray'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/45/b7/45b77ab57a7dbf0578b26d36f8c2258e0762dda6.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0945202006.html',
    },
    {
      id: 'long-sleeved-regular-ft-shirt-0',
      name: 'Long-sleeved Regular Ft Shirt',
      brand: 'H&M',
      category: 'tshirts',
      type: 'men',
      sizes: [
        { name: 'XXS', inStock: true },
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: true },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
        { name: 'XXXL', inStock: false },
      ],
      price: 10000,
      rating: 3.9,
      reviewCount: 117,
      colors: ['white'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/e6/0f/e60f46701320cc38ac76dbb48c62ee3acc7f54cc.jpg],origin[dam],category[men_tshirtstanks_longsleeve],type[DESCRIPTIVESTILLLIFE],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0596400008.html',
    },
    {
      id: 'printed-t-shirt-0',
      name: 'Printed T-shirt',
      brand: 'H&M',
      category: 'tshirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 12000,
      rating: 3.6,
      reviewCount: 7,
      colors: ['green', 'beige'],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/2a/3d/2a3d11c51f735ca7b92bd597f80d9ca3cba060be.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0684021150.html',
    },
    {
      id: '3-pack-regular-fit-tshirts',
      name: '3-pack Regular Fit T-shirts',
      brand: 'H&M',
      category: 'tshirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 19000,
      rating: 3.6,
      reviewCount: 5,
      colors: ['darkgray', 'orange', 'beige'],
      description: 'Crew-neck T-shirts in soft cotton jersey.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/a6/5b/a65b2a81ff0c018879cad9c5c4437887893a88b9.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0945531006.html',
    },
    {
      id: 'relaxed-fit-tshirt',
      name: 'Relaxed Fit T-shirt',
      brand: 'H&M',
      category: 'tshirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 19000,
      rating: 4.3,
      reviewCount: 17,
      colors: ['white', 'black'],
      description:
        'Relaxed-fit T-shirt in soft cotton jersey with a printed design. Ribbed crew neck and dropped shoulders.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/c4/b8/c4b82f8dfc39e7968ed9ae11eb33d84ae32a84b8.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[w],hmver[2]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0972640024.html',
    },
    {
      id: 'printed-tshirt',
      name: 'Printed T-shirt',
      brand: 'H&M',
      category: 'tshirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 9000,
      rating: 4.3,
      reviewCount: 17,
      colors: ['white', 'beige'],
      description: 'T-shirt in soft cotton jersey with a printed graphic design and crew neck.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=source[/1a/82/1a827c34f867be3a22d358b30dde18b901f058ef.jpg],origin[dam],category[],type[LOOKBOOK],res[w],hmver[1]&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0684021149.html',
    },
    {
      id: 'regular-fit-shirt-jacket',
      name: 'Regular Fit Shirt Jacket',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 26000,
      rating: 0,
      reviewCount: 0,
      colors: ['black', 'darkkhaki', 'cream', 'brown', 'steelblue', 'darkgreen'],
      description:
        'Shirt jacket in cotton twill. Collar, classic button placket, open chest pockets, and yoke at back. Long sleeves with sleeve placket and buttons at cuffs. Rounded hem.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fe5%2Fce%2Fe5ce1549abffe10405626579e36718d562334101.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0944940016.html',
    },
    {
      id: 'regular-fit-shirt-jacket1',
      name: 'Regular Fit Shirt Jacket',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 26000,
      rating: 0,
      reviewCount: 0,
      colors: ['beige', 'darkkhaki', 'cream', 'brown', 'steelblue', 'darkgreen'],
      description:
        'Shirt jacket in cotton twill. Collar, classic button placket, open chest pockets, and yoke at back. Long sleeves with sleeve placket and buttons at cuffs. Rounded hem.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fa6%2Fd4%2Fa6d44d8dce427daac28a5339065ccbec01c9c134.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0944940017.html',
    },
    {
      id: 'slim-fit-easy-shirt0',
      name: 'Slim Fit Easy-iron Shirt',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 18000,
      rating: 4.0,
      reviewCount: 2,
      colors: ['lightblue', 'black', 'white', 'maroon', 'darkblue'],
      description:
        'Long-sleeved shirt in woven fabric with an easy-iron finish. Turn-down collar, classic button placket, and darts and yoke at back. Narrow cuffs with adjustable buttoning. Rounded hem. Slim Fit – narrow shoulders and tapered waist for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F16%2Fe5%2F16e57bfc58d7e92eaecde9bd3180e51b4095320f.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_shirts_dressed%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0781758004.html',
    },
    {
      id: 'slim-fit-easy-shirt1',
      name: 'Slim Fit Easy-iron Shirt',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 18000,
      rating: 4.0,
      reviewCount: 2,
      colors: ['black', 'lightblue', 'white', 'maroon', 'darkblue'],
      description:
        'Long-sleeved shirt in woven fabric with an easy-iron finish. Turn-down collar, classic button placket, and darts and yoke at back. Narrow cuffs with adjustable buttoning. Rounded hem. Slim Fit – narrow shoulders and tapered waist for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F9a%2F83%2F9a83a2ddd33afc2e826b5e69caf849e8ae439f7a.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_shirts_dressed%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0781758004.html',
    },
    {
      id: 'slim-fit-easy-shirt2',
      name: 'Slim Fit Easy-iron Shirt',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 18000,
      rating: 4.0,
      reviewCount: 2,
      colors: ['white', 'lightblue', 'black', 'maroon', 'darkblue'],
      description:
        'Long-sleeved shirt in woven fabric with an easy-iron finish. Turn-down collar, classic button placket, and darts and yoke at back. Narrow cuffs with adjustable buttoning. Rounded hem. Slim Fit – narrow shoulders and tapered waist for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fdc%2F5c%2Fdc5c66bee2ca8ce5cf280e0744162c3c1ef18c31.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_shirts_dressed%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0781758004.html',
    },
    {
      id: 'cotton-flannel-shirt-0',
      name: 'Cotton Flannel Shirt',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 26000,
      rating: 0,
      reviewCount: 0,
      colors: ['red', 'black', 'beige'],
      description:
        'Plaid shirt in soft cotton flannel. Turn-down collar, classic button placket, yoke at back, and two open chest pockets. Long sleeves with adjustable buttoning at cuffs and a sleeve placket with link button. Rounded hem.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fe6%2F68%2Fe668e0d523501ae79346c5cec7b0a87ded73a9d7.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0908891001.html',
    },
    {
      id: 'cotton-flannel-shirt-1',
      name: 'Cotton Flannel Shirt',
      brand: 'H&M',
      category: 'shirts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 26000,
      rating: 0,
      reviewCount: 0,
      colors: ['red', 'black', 'beige'],
      description:
        'Plaid shirt in soft cotton flannel. Turn-down collar, classic button placket, yoke at back, and two open chest pockets. Long sleeves with adjustable buttoning at cuffs and a sleeve placket with link button. Rounded hem.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F98%2F03%2F98031caf3beda16b3ee1f6ef0a59df30b51218e4.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_shirts_flannel%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0908891001.html',
    },
    {
      id: 'cotton-shorts-0',
      name: 'Cotton Shorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 25000,
      rating: 0,
      reviewCount: 0,
      colors: ['steelblue', 'beige', 'darkblue', 'gray'],
      description:
        'Shorter-cut shorts in woven cotton fabric. Waistband with covered elastic, drawstring, and mock fly. Side-seam pockets and back pockets with hook-loop fastening.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fec%2F13%2Fec13f467fb22df3a172c82135e3fa69a00a32077.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0977734001.html',
    },
    {
      id: 'cotton-shorts-1',
      name: 'Cotton Shorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 25000,
      rating: 0,
      reviewCount: 0,
      colors: ['beige', 'steelblue', 'darkblue', 'gray'],
      description:
        'Shorter-cut shorts in woven cotton fabric. Waistband with covered elastic, drawstring, and mock fly. Side-seam pockets and back pockets with hook-loop fastening.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fd2%2F3c%2Fd23c4d5c735f4409dccb3325e4f713c39958e5c1.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0977734001.html',
    },
    {
      id: 'cotton-shorts-2',
      name: 'Cotton Shorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 25000,
      rating: 0,
      reviewCount: 0,
      colors: ['darkblue', 'steelblue', 'beige', 'gray'],
      description:
        'Shorter-cut shorts in woven cotton fabric. Waistband with covered elastic, drawstring, and mock fly. Side-seam pockets and back pockets with hook-loop fastening.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F08%2F9f%2F089f491a1fe6862904f0cb315119203f7ea4e1b9.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0977734001.html',
    },
    {
      id: 'cotton-shorts-3',
      name: 'Cotton Shorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 19000,
      rating: 0,
      reviewCount: 0,
      colors: ['gray', 'steelblue', 'beige', 'darkblue'],
      description:
        'Shorter-cut shorts in woven cotton fabric. Waistband with covered elastic, drawstring, and mock fly. Side-seam pockets and back pockets with hook-loop fastening.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fc7%2F86%2Fc7860f44f302a0fbaa7e95c7a8c5c88265f9db0d.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0977734001.html',
    },
    {
      id: 'regular-fit-sweatshorts-0',
      name: 'Regular Fit Sweatshorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 19000,
      rating: 0,
      reviewCount: 0,
      colors: ['darkgreen	', 'black', 'white'],
      description:
        'Sweatshorts in lightweight cotton fabric. Waistband with covered elastic and a drawstring. Welt side pockets, open back pocket, and a printed detail on one leg.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F68%2Fbc%2F68bcdc197575b70b4e49cc13c28294771cee18d7.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0972555003.html',
    },
    {
      id: 'regular-fit-sweatshorts-1',
      name: 'Regular Fit Sweatshorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 19000,
      rating: 0,
      reviewCount: 0,
      colors: ['black	', 'darkgreen', 'white'],
      description:
        'Sweatshorts in lightweight cotton fabric. Waistband with covered elastic and a drawstring. Welt side pockets, open back pocket, and a printed detail on one leg.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fd0%2F59%2Fd05901b2be1d9d3b570d2cf8c90ba62c0d4e9473.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0972555003.html',
    },
    {
      id: 'regular-fit-sweatshorts-2',
      name: 'Regular Fit Sweatshorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 19000,
      rating: 0,
      reviewCount: 0,
      colors: ['white	', 'darkgreen', 'black'],
      description:
        'Sweatshorts in lightweight cotton fabric. Waistband with covered elastic and a drawstring. Welt side pockets, open back pocket, and a printed detail on one leg.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Ff3%2Fb7%2Ff3b7b0b68796982be5add3ceb23e78d9cedcd444.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0972555003.html',
    },
    {
      id: 'patterned-sweatshorts',
      name: 'Patterned Sweatshorts',
      brand: 'H&M',
      category: 'shorts',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: true },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: true },
      ],
      price: 26000,
      rating: 0,
      reviewCount: 0,
      colors: ['lightpink'],
      description:
        'Sweatshorts with a printed pattern. Elasticized drawstring waistband, side pockets, and a back pocket.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fc7%2F58%2Fc75827c866923988ab1fc37e13319d1387827d67.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0847065024.html',
    },
    {
      id: 'skinny-fit-cargo-joggers-0',
      name: 'Skinny Fit Cargo Joggers',
      brand: 'H&M',
      category: 'pants',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 38000,
      rating: 0,
      reviewCount: 0,
      colors: ['black', 'beige'],
      description:
        'Chinos in extra-stretchy cotton twill. Zip fly, side pockets, coin pocket, and welt back pockets with button. Slim Fit – close-fitting at thighs, knees, and ankles for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F1f%2F33%2F1f33d1935d739050e96e44055eab1118f51448f2.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0997065001.html',
    },
    {
      id: 'skinny-fit-cargo-joggers-1',
      name: 'Skinny Fit Cargo Joggers',
      brand: 'H&M',
      category: 'pants',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 38000,
      rating: 0,
      reviewCount: 0,
      colors: ['beige', 'black'],
      description:
        'Chinos in extra-stretchy cotton twill. Zip fly, side pockets, coin pocket, and welt back pockets with button. Slim Fit – close-fitting at thighs, knees, and ankles for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F99%2F21%2F992189e4e5b2cd35a8c70dd8871a588b8e4f344a.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0997065001.html',
    },
    {
      id: 'slim-fit-chinos-0',
      name: 'Slim Fit Chinos',
      brand: 'H&M',
      category: 'pants',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 30000,
      rating: 0,
      reviewCount: 0,
      colors: ['burlywood', 'black', 'brown', 'darkgray', 'blue'],
      description:
        'Chinos in extra-stretchy cotton twill. Zip fly, side pockets, coin pocket, and welt back pockets with button. Slim Fit – close-fitting at thighs, knees, and ankles for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F33%2F19%2F3319f5e0465ba86a677ee245bd3c4f8ff17c5b89.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0815456044.html',
    },
    {
      id: 'slim-fit-chinos-1',
      name: 'Slim Fit Chinos',
      brand: 'H&M',
      category: 'pants',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 30000,
      rating: 0,
      reviewCount: 0,
      colors: ['black', 'burlywood', 'brown', 'darkgray', 'blue'],
      description:
        'Chinos in extra-stretchy cotton twill. Zip fly, side pockets, coin pocket, and welt back pockets with button. Slim Fit – close-fitting at thighs, knees, and ankles for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fb0%2Fad%2Fb0adf9a5dfbf6804f79ec0fdd73978e89d501f42.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_trousers_chinos_slim_all%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0815456044.html',
    },
    {
      id: 'slim-fit-chinos-2',
      name: 'Slim Fit Chinos',
      brand: 'H&M',
      category: 'pants',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 30000,
      rating: 0,
      reviewCount: 0,
      colors: ['blue', 'burlywood', 'brown', 'darkgray', 'black'],
      description:
        'Chinos in extra-stretchy cotton twill. Zip fly, side pockets, coin pocket, and welt back pockets with button. Slim Fit – close-fitting at thighs, knees, and ankles for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F83%2F45%2F8345878108cc403669ef2bb8572c313a4bec7756.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0815456044.html',
    },
    {
      id: 'slim-jeans-0',
      name: 'Slim Jeans',
      brand: 'H&M',
      category: 'jeans',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 28000,
      rating: 0,
      reviewCount: 0,
      colors: ['darkblue', 'white'],
      description: '5-pocket jeans in washed denim with a regular waist, zip fly, and slim legs.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F36%2F49%2F3649b9506787743b7d4b0e5f8014d13946bf3632.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_jeans_slim%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0636207001.html',
    },
    {
      id: 'slim-jeans-1',
      name: 'Slim Jeans',
      brand: 'H&M',
      category: 'jeans',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 28000,
      rating: 0,
      reviewCount: 0,
      colors: ['white', 'darkblue'],
      description: '5-pocket jeans in washed denim with a regular waist, zip fly, and slim legs.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F44%2F46%2F4446a90f38fd1e40860fa2bc9149605d2de2cfd7.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_jeans_slim%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0636207001.html',
    },
    {
      id: 'relaxed-tapered-pullon-jeans-0',
      name: 'Relaxed Tapered Pull-on Jeans',
      brand: 'H&M',
      category: 'jeans',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 48000,
      rating: 3,
      reviewCount: 3,
      colors: ['darkblue', 'black'],
      description:
        'Ankle-length, 5-pocket jeans in thick cotton denim. Regular waist, waistband with covered elastic at back, and zip fly with button. Wide, tapered legs.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F99%2F25%2F992512ac6e0041a3b4e09436160e061fa30b8774.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0986779004.html',
    },
    {
      id: 'relaxed-tapered-pullon-1',
      name: 'Relaxed Tapered Pull-on Jeans',
      brand: 'H&M',
      category: 'jeans',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 48000,
      rating: 3,
      reviewCount: 3,
      colors: ['black', 'darkblue'],
      description:
        'Ankle-length, 5-pocket jeans in thick cotton denim. Regular waist, waistband with covered elastic at back, and zip fly with button. Wide, tapered legs.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F9a%2F69%2F9a69da3df305a2f150b77952c13ac524ecfbed29.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0986779004.html',
    },
    {
      id: 'slim-fit-linen-blazer-0',
      name: 'Slim Fit Linen Blazer',
      brand: 'H&M',
      category: 'suits',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 48000,
      rating: 3,
      reviewCount: 3,
      colors: ['beige', 'darkblue'],
      description:
        'Single-breasted blazer in woven linen fabric. Narrow, notched lapels with decorative buttonhole. Chest pocket, front pockets with flap, and two inner pockets. Two buttons at front, decorative buttons at cuffs, and vent at back. Lined. Slim Fit – tapered at chest and waist with slightly narrower sleeves for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fc8%2Fd8%2Fc8d8e6c17b2f06e20d9ecc72df49eba69e66f36b.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_blazerssuits_blazers%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0783354005.html',
    },
    {
      id: 'slim-fit-linen-blazer-1',
      name: 'Slim Fit Linen Blazer',
      brand: 'H&M',
      category: 'suits',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 48000,
      rating: 3,
      reviewCount: 3,
      colors: ['darkgray', 'beige'],
      description:
        'Single-breasted blazer in woven linen fabric. Narrow, notched lapels with decorative buttonhole. Chest pocket, front pockets with flap, and two inner pockets. Two buttons at front, decorative buttons at cuffs, and vent at back. Lined. Slim Fit – tapered at chest and waist with slightly narrower sleeves for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fc9%2Fae%2Fc9aeca109a02462d5d20f72a2b051970517b41a4.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_blazerssuits_blazers%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0783354005.html',
    },
    {
      id: 'suit-blazer-0',
      name: 'Gray Skinny Fit Suit Blazer',
      brand: 'H&M',
      category: 'suits',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 58000,
      rating: 5,
      reviewCount: 1,
      colors: ['gray'],
      description:
        'Single-breasted blazer in woven stretch fabric with narrow, notched lapels. Chest pocket, front pockets with flap, and an inner pocket. Decorative buttons at cuffs and a vent at back. Lined. Skinny Fit – slightly shorter style, shaped at chest, tapered sharply at waist, combined with narrow shoulders and sleeves for a completely tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F55%2Fb7%2F55b76397eca7d79907a138046f643cbe977724e5.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_blazerssuits_blazers%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0713995004.html',
    },
    {
      id: 'slim-blazer-0',
      name: 'Slim Fit Blazer',
      brand: 'H&M',
      category: 'suits',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 63000,
      rating: 5,
      reviewCount: 1,
      colors: ['lightgray', 'dimgray'],
      description:
        'Single-breasted blazer in woven fabric. Pointed lapels, chest pocket, welt front pockets, and an inner pocket. Long sleeves with decorative buttons at cuffs. Vent at back. Lined. Slim Fit – tapered at chest and waist with slightly narrower sleeves for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F27%2F8d%2F278d664a912e99cf03402197c3e69fda11ccaae9.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0912352009.html',
    },
    {
      id: 'slim-blazer-1',
      name: 'Slim Fit Blazer',
      brand: 'H&M',
      category: 'suits',
      type: 'men',
      sizes: [
        { name: 'XS', inStock: false },
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
        { name: 'XXL', inStock: false },
      ],
      price: 63000,
      rating: 5,
      reviewCount: 1,
      colors: ['dimgray', 'lightgray'],
      description:
        'Single-breasted blazer in woven fabric. Pointed lapels, chest pocket, welt front pockets, and an inner pocket. Long sleeves with decorative buttons at cuffs. Vent at back. Lined. Slim Fit – tapered at chest and waist with slightly narrower sleeves for a tailored silhouette.',
      imgUrl:
        'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fdd%2F36%2Fdd36eabb2fb8d4a66e9f2b04aa9831366e527d77.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_blazerssuits_blazers%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
      url: 'https://www2.hm.com/en_us/productpage.0912352009.html',
    },
  ],
  countries: [
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'AndorrA', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, The Democratic Republic of the', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: "Cote D'Ivoire", code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { name: 'Holy See (Vatican City State)', code: 'VA' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic Of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: "Korea, Democratic People'S Republic of", code: 'KP' },
    { name: 'Korea, Republic of', code: 'KR' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: "Lao People'S Democratic Republic", code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macao', code: 'MO' },
    { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'RWANDA', code: 'RW' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia and Montenegro', code: 'CS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },
    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.S.', code: 'VI' },
    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' },
  ],
}
